//! Android entry point.
//!
//! Compiled only for Android, into the `cdylib` the APK loads. The
//! [`bevy_main`](bevy::bevy_main) macro emits the `android_main` symbol that
//! Android's GameActivity calls, and Bevy wires the `AndroidApp` into
//! [`bevy::winit`] behind the scenes.
//!
//! Like the browser build, Android uses the rosbridge transport only (DDS
//! multicast is unreliable on mobile networks), so this crate must be built
//! with `--no-default-features --features rosbridge`. The app launches the
//! embedded NAO demo so it shows something useful out of the box; from there
//! the runtime connection bar (see [`crate::connection_ui`]) lets the user
//! type a rosbridge URL and switch to a live robot.

use bevy::prelude::*;

use crate::options::Options;

/// Android application entry point. `android_main` is generated by
/// [`bevy_main`](bevy::bevy_main); it forwards into the shared
/// [`crate::app::run`] just like the desktop binary and the wasm `start`.
#[bevy_main]
pub fn main() {
    let options = Options {
        // No CLI/connect UI on device yet — show the embedded demo.
        demo: true,
        ..Options::default()
    };
    // `run` only returns on app exit.
    let _ = crate::app::run(options);
}
